version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  valkey:
    image: valkey/valkey:8.0.1-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/data

volumes:
  postgres-data:
  valkey-data:
