services:
  app:
    container_name: app # This is the name of the container when you run `docker ps`, not the name of the service in the `devcontainer.json` file
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/app:cached
    command: sleep infinity
  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  valkey:
    image: valkey/valkey:8.0.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/data

volumes:
  postgres-data:
  valkey-data:
